src/genlab_bestilling/libs/genlabid.py
Based on a request from Kristin.
=> chg: compute genlabid based on the year of the order

pyproject.toml, uv.lock
=> Remove group tools.

src/staff/views.py
=> Superuser should always have perms.

src/genlab_bestilling/admin.py
=> Register missing models in admin panel.

src/staff/templates/staff/dashboard.html, src/staff/views.py, src/static/js/staff/dashboard.js, src/static/js/utils.js
Displays orders that are confirmed on the dashboard frontpage in a box. Clicking the order will send the user to the order page.
Builds on #84
=> Displays orders that are confirmed on the dashboard frontpage

docker-compose.yml, entrypoint.sh
=> Allow disabling of db await.

src/capps/users/admin.py
=> Register Permission.

src/genlab_bestilling/admin.py
=> Improve SampleAdmin.

src/genlab_bestilling/admin.py, src/genlab_bestilling/models.py
=> Improve ExtractionOrderAdmin.

src/genlab_bestilling/admin.py
=> Add order filter.

src/staff/tables.py, src/templates/django_tables2/tailwind.html
The sorting of the tables is done in a .py file, not in the tailwind.html file.
Minimal changes in the tailwind.html file, with an addition of arrows on columns that are orderable.
=> Generalise out of template

src/staff/templates/staff/dashboard.html, src/staff/views.py
Fixes typo in declaring delivered orders. Suspect something went wrong in a previous merge conflict.
=> Fix typo confirmed -> delivered

src/genlab_bestilling/admin.py, src/genlab_bestilling/api/serializers.py, src/genlab_bestilling/models.py
=> Display fish_id in admin.

src/genlab_bestilling/admin.py
=> Improve ExtractPlatePositionAdmin.

src/genlab_bestilling/admin.py
=> Improve SpeciesAdmin.

src/genlab_bestilling/admin.py, src/genlab_bestilling/models.py
=> Improve AnalysisResultAdmin.

src/genlab_bestilling/admin.py
=> Improve AreaAdmin.

src/genlab_bestilling/admin.py
=> Improve LocationAdmin.

src/genlab_bestilling/admin.py
=> Improve SampleTypeAdmin.

src/genlab_bestilling/admin.py
=> Improve EquipmentTypeAdmin.

src/genlab_bestilling/admin.py
=> Improve EquipmentBufferAdmin.

src/staff/templates/staff/analysisorder_detail.html
Staff should be able to convert a delivered order to draft.
Staff should also be able to convert an analysis order to processing and complete.
=> Able to change status and convert to draft for analysis orders

src/staff/tables.py, src/staff/templates/staff/dashboard.html, src/staff/templatetags/order_tags.py
=> Add table for draft orders to dashboard

src/staff/tables.py, src/staff/templates/staff/sample_lab.html, src/staff/urls.py, src/staff/views.py
- Updated sample table to include isolation_method field.
- Enhanced sample_lab.html to support selection of isolation methods.
- Refactored SampleLabView to retrieve and update isolation methods for samples.
- Changed URL and view for updating internal notes to improve clarity.
=> Add isolation method handling in sample status page

src/staff/tables.py, src/staff/templates/staff/sample_lab.html
Update back button link in sample_lab.html
=> Add 'type' column to SampleStatusTable 

src/staff/tables.py, src/staff/templatetags/order_tags.py
Adds priority to urgent order table on the dashboard.
=> Add priority to urgent orders table

src/staff/tables.py, src/staff/templatetags/order_tags.py
Counts isolated samples on extraction orders.
=> Count isolated samples

src/genlab_bestilling/managers.py, src/genlab_bestilling/models.py, src/genlab_bestilling/tests/test_models.py, src/staff/tables.py, src/staff/views.py
=> Fix name sorting

src/staff/tables.py, src/staff/templates/staff/components/priority_column.html, src/staff/views.py
=> Style analysis and extraction table

src/staff/templates/staff/analysisorder_detail.html, src/staff/templates/staff/components/seen_column.html, src/staff/templates/staff/extractionorder_detail.html, src/staff/templatetags/order_tags.py, src/staff/views.py
All staff members can now see the "Mark as seen" button, and mark as seen.
=> All staff can mark as seen

src/capps/users/forms.py, src/capps/users/managers.py, src/genlab_bestilling/api/serializers.py, src/genlab_bestilling/forms.py, src/genlab_bestilling/managers.py, src/genlab_bestilling/models.py, src/nina/forms.py, src/nina/tables.py, src/staff/forms.py, src/staff/tables.py, src/staff/views.py
=> More mypy.

pyproject.toml, src/capps/users/managers.py, src/genlab_bestilling/forms.py, src/genlab_bestilling/models.py, src/genlab_bestilling/views.py, src/manage.py, src/nina/forms.py
=> Add ruff EM rules.

pyproject.toml, src/capps/core/management/commands/wait_for_http.py, src/genlab_bestilling/forms.py, src/genlab_bestilling/models.py, src/genlab_bestilling/tests/test_e2e.py
=> Add ruff ISC rules.

.pre-commit-config.yaml, pyproject.toml, src/capps/users/adapters.py, src/capps/users/apps.py, src/genlab_bestilling/api/views.py, src/genlab_bestilling/apps.py, src/genlab_bestilling/forms.py, src/genlab_bestilling/managers.py, src/genlab_bestilling/tests/test_models.py, src/shared/sentry.py, src/staff/templatetags/table_header_tag.py
=> Add ruff SIM rules.

src/staff/views.py
I couldn't get mypy to display errors in vscode, but I would think this solves the errors that were mentioned. This should however be double checked.
=> Fix update isolation method logic

src/genlab_bestilling/forms.py, src/genlab_bestilling/templates/genlab_bestilling/widgets/custom_checkbox.html
I was unable to find a better way to do this. Also, adding styling to the widget-label seemed to be a problem. However, it was approved by the designer.
=> Add label above "is_urgent" checkbox

src/nina/admin.py
=> Improve ProjectMembershipAdmin.

src/capps/core/templates/core/partials/navigation.html, src/staff/templates/staff/base.html, src/templates/core/partials/navigation.html
- Sidebar navigation and content doesn't collide
- Sidebar navigation goes above main content on smaller screens
https://github.com/user-attachments/assets/66e58081-0ef5-4cf1-8600-a0c6b5e56edc
=> Improve dashboard overflow

src/staff/mixins.py
Ref https://github.com/NINAnor/genlab_bestilling/pull/407#discussion_r2227965637
=> Remove repetitive code from SafeRedirectMixin

src/capps/core/templatetags/core.py, src/staff/templates/staff/equipmentorder_detail.html, src/staff/templates/staff/extractionplate_detail.html, src/staff/templates/staff/project_detail.html, src/staff/templates/staff/sample_detail.html, src/templates/components.yaml, src/templates/components/object-detail-staff.html
Also removed responsible staff as a field when placing an order.
=> 423 remove is seen and is prioritized from table in a order

src/genlab_bestilling/models.py, src/staff/views.py
Order will be set to processing or completed after being a draft if it has already been in those states
=> Status logic

src/staff/templates/staff/analysisorder_detail.html
Remove "Set as processing" and "set to complete"-buttons
=> Remove unnecessary buttons

src/genlab_bestilling/api/serializers.py
Ref: https://github.com/NINAnor/genlab_bestilling/pull/291#discussion_r2227989837
=> Implement custom field

src/staff/filters.py, src/staff/tables.py, src/staff/templates/staff/components/activation_toggle_column.html, src/staff/templates/staff/components/project_verified_column.html, src/staff/templates/staff/components/seen_column.html, src/staff/templates/staff/project_detail.html, src/staff/urls.py, src/staff/views.py
- Introduced ProjectFilter for filtering projects by number, name, verified status, and active status.
- Updated ProjectTable to include a toggle for project activation.
- Created templates for project verification and activation buttons.
- Added ProjectArchiveActionView to handle project activation state changes.
- Updated URLs to include the new archive action for projects.
=> Add project filtering and activation features

src/genlab_bestilling/admin.py, src/genlab_bestilling/models.py, src/staff/templates/staff/sample_detail.html
=> Sample admin-panel link.

src/staff/filters.py, src/staff/tables.py, src/staff/views.py
Same as https://github.com/NINAnor/genlab_bestilling/pull/500 but with summer25-week-32 as origin branch. 
It was approved by @omfj in https://github.com/NINAnor/genlab_bestilling/pull/500 .
=> Filter for EquipmentOrder page

src/staff/views.py
Fixes error from sorting SampleTable
Closes #527
=> Annotate numeric name.
